### PR TITLE
Submission from davideserafini

### PR DESCRIPTION
**Pull request by davideserafini**
Hello, here's my submission for the bounty "Crypto-Market Application Using Bluzelle".

All the details are in the README file and in the email.

Feel free to contact me for any issue, especially those I've highlighted in the email in case.

Regards,
Davide

### CODE REVIEW

**Comment by davideserafini** [comment]
Hello @njmurarka, any news about this bounty?

**Comment by njmurarka** [comment]
Hello and thanks for your patience. Apologies for the delay.

Can you send me an email? neeraj AT bluzelle DOT com.

**Review by matteyu — CHANGES_REQUESTED** [review]
Hi @davideserafini 

I'm one of the delegated reviewers by @njmurarka.  I've taken a quick look in this PR and compared it to your own repo.  I know this PR is a bit outdated but I did notice that for the chain ID and the rest endpoint, they are still hard-coded.  Is it possible to convert those over to process variables as well?

So mnemonics, uuid, chain id, and endpoint should all go in the .env file

Similarly for the frontend, perhaps the dotenv package can also be utilized in there and we can centralize these values in a .env file as well.  Not having the values hardcoded will give the project flexibility to be pointed to different environments (whether it be testnet public or mainnet)

**Comment by davideserafini** [comment]
Hello @matteyu, I've updated the code and also changed both frontend and backend code to use environment variables.

**Pull request merged**
