### PR TITLE
Submission from Will

### PR DESCRIPTION
**Pull request by WillXing**
Hi, please review my submission, all the details are in README as required

### CODE REVIEW

**Comment by njmurarka** [comment]
Is the live demo working? I does not seem to load up.

**Comment by WillXing** [comment]
Hi @njmurarka , it's because I am keep getting timeout after I save the data couple times from the backend. Is there any limitation of the api usage?

**Comment by njmurarka** [comment]
There probably are some sort of limits on API usage.

Can you try a different API key and reduce the frequency of using the API? How do you do it? Do you request the latest data only when the client connects? Or something else?

**Comment by WillXing** [comment]
I created another store with new api key. and make the frequency to every 15mins. It will save 20+ times since it's the data with pagination.
Can you try it again: http://crypto-market-web-app.s3-website-ap-southeast-2.amazonaws.com/

The approach is quite straight forward, the backend is query data from the `coingecko`  250 items per page, and then save it to the store with the page number as key.
When new data coming, it will overwrite the old data.

So frontend always get the latest data.

**Comment by njmurarka** [comment]
It worked last night (24 hrs ago) but it is not working again (on this new link).

Can you take a look please? A call every 15 mins probably should not block the API.

**Comment by WillXing** [comment]
There's no new error log coming anymore after change the interval and the data is loading fine, what error you got on your side?

**Comment by njmurarka** [comment]
Not sure about an error log but when I goto "
http://crypto-market-web-app.s3-website-ap-southeast-2.amazonaws.com", the
app simply does not load -- it just shows the loading "bar". forever. I
would really like to see this working as part of the submission.

**Comment by WillXing** [comment]
Can you help me to debug this issue by open your console and show me the error log? I can't reproduce this on my side some how.

**Comment by njmurarka** [comment]
Hi Will. Can you share your YouTube video again?

I am referring to the following video:

http://youtu.be/hhTt3DhvsB8

**Pull request closed without merging**
